### ISSUE TITLE
The property name '<form field>' is not valid

### ISSUE THREAD

**Issue by al3x-edge** [blueriver/MuraCMS#1596] opened 2014-09-22 16:00 UTC
`The property name 'phone' is not valid` is a message I get off a client site when a field is not required, but validation is attached to the field; numeric validation in this case.  This is using the form builder on version 6.1.6062, but affected a previous version in the 59xx area as well (didn't check before upgrade today).

I am unable to find where validation occurs on the form fields for the form builder forms (or in general) otherwise I would submit a patch.  If time is an issue, pointing me near a file / line number will allow me to submit a patch to fix.

**Comment by stevewithington** [comment] 2015-02-13 22:34
Closing as unable to reproduce. If you have a specific example, please feel free to re-open and submit it and/or point us to a URL to reproduce.

**Closed by stevewithington** 2015-02-13 22:34 UTC

**Comment by pdayquotient** [comment] 2015-03-02 15:08
I am experiencing this issue as well.

My form field configuration:

![screen shot 2015-03-02 at 10 10 17 am](https://cloud.githubusercontent.com/assets/11273264/6443280/d1f952ae-c0c3-11e4-8212-33022c2b2860.png)

The form:

![screen shot 2015-03-02 at 10 11 31 am](https://cloud.githubusercontent.com/assets/11273264/6443298/edeaa6f2-c0c3-11e4-9b15-f395053c82d6.png)

The outcome:

![screen shot 2015-03-02 at 10 12 11 am](https://cloud.githubusercontent.com/assets/11273264/6443305/0558d958-c0c4-11e4-93f7-61c55edf388e.png)


Now, if i place a value in the email field, it will work. But if I submit blank, I always get "The property name 'email' is not valid."

**Comment by al3x-edge** [comment] 2015-03-04 14:53
@pdayquotient, did you have a post here and delete it? Wasn't going to example it after you posted something, but might track this down again if you backtracked.

**Comment by pdayquotient** [comment] 2015-03-04 14:56
Thank you! Was just getting ready to enter that reference in.
