### ISSUE TITLE
Info button modal shows up, then disappears. 

### ISSUE THREAD

**Issue by dmoncado** [blueriver/MuraCMS#2905] opened 2018-06-25 22:00 UTC
Clicking the info button launches the modal to display information about the uploaded image works but… then it immediately disappears :disappointed: Just FYI!

![screen shot 2018-06-25 at 11 16 08 am](https://user-images.githubusercontent.com/4700158/41878028-5b3d59d2-7888-11e8-8acf-444f17b72b2d.png)

Also: here's a quick screen recording
https://www.useloom.com/share/0a2f53c526ff4380a447fb939629eccf

**Comment by mattlevine** [comment] 2018-06-26 00:38
This issue was caused by a recent jquery update. I fixed it in this commit which will be in the next build

https://github.com/blueriver/MuraCMS/commit/5b73ac6c066cde7a814d02d75f73e2368386ca17

**Closed by mattlevine** 2018-06-26 00:38 UTC
