### ISSUE TITLE
Form submission broken -marked as spam

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2601] opened 2017-06-16 13:17 UTC
Hi chaps, 

Been having trouble getting form submissions to work properly for me, fine locally, up on the server they all get marked as spam.

Server is: CentOS, Nginx, Lucee, MySQL, Mura 7.0.xxxx, Varnish.

I suspect the issues I have is something to do with Varnish in my case, though I am not the only one in the Google group to experience the same issues:

https://groups.google.com/forum/#!searchin/mura-cms-developers/spam%7Csort:relevance/mura-cms-developers/_RhtBnl-cBw/aBPkiDLBhKIJ

When submitting, I've deduced via some debugging that the form is being rejected as spam due to this block: 

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/content/dataCollection/dataCollectionBean.cfc#L256-L260

Now I am not absolutely sure what this is doing, but best guess by var naming is that it is checking Lucee/CF sessions to see whether it is a bot just trying to force a form submission without having been on the site yet.

Be great to hear back from on what you think about the issue above!

Many thanks!

Peter.

**Comment by Tigerlady** [comment] 2017-07-18 18:28
I am having this same issue, only I am on a Windows 2008 server, Lucee 05.  I just did an update to the core and site files.  Cleared my cache and history.  Then tried the form submit again and am still having issues with the form being marked as spam.  The form is built with the built in form builder.  I have a few sites that seem to be having the same issue. 

Thanks.

**Comment by mattlevine** [comment] 2017-07-18 22:53
@tigerlady What version of Mura are you on? If you're on 6 what version site version is it?

**Comment by mattlevine** [comment] 2017-07-18 22:53
Does the problem happen caching turned both on and off?

**Comment by Tigerlady** [comment] 2017-07-19 13:02
Matt,  We are using version 7 and just updated to the latest core version 7020.  Also whether caching is turn on or off doesn't make a difference.  I have one site where the cache is turned on and another where it is turned off, both have the same behavior.

**Comment by mattlevine** [comment] 2017-07-31 19:55
Would either of you be able to give me access to a Mura instance that is having this problem?

Otherwise you may want to just use method injection to replace Mura's CFFormprotect method to always return true;

```
function onApplicationLoad(m){
        m.getBean('utility').inject('cfformprotect',cfformprotect_replacement);

}

function cfformprotect_replacement(){
       return true;
}

```

Sorry for the slow response . 
-Matt

**Comment by Tigerlady** [comment] 2017-08-01 13:02
Matt,  I know that you have closed this I didn't see your request yesterday about access.  I can set up access for you.  I updated one of the sites having issues just this morning to the latest version of Mura and am still having the issue of the form not submitting. 

https://www.chamberbyohare.org/membership-application/   

after filling out the form hit submit nothing happens.  In the web console, I get this 

TypeError: c.data is undefined[Learn More]  mura.min.js:4:2242

**Comment by PeterBowater** [comment] 2017-08-01 15:15
Thanks @Tigerlady , more tricky for me to give access I'm afraid, appreciate you pushing on with it!


Peter.

**Comment by mattlevine** [comment] 2017-08-01 18:35
OK, please update and retest once more.  I believe that at least part of the problem is now fixed.  I think the issue cropped up when using ReCaptcha from within a cluster where cgi.remote_addr was not correct.  Mura actually already has logic to use the IP that the load balancer forwarded over and sets it to request.remoteAddr. 

https://github.com/blueriver/MuraCMS/blob/develop/config/appcfc/onRequestStart_include.cfm#L187-L200

Another issue, that could cause this problem is if your server is behind a proxy and can't get out of your network.  If that's the case you can set proxy settings in the setting.ini.cfm

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/reCAPTCHA.cfc#L80-L86

-Matt

**Comment by PeterBowater** [comment] 2017-08-02 08:01
Thanks @mattlevine , that does seem to have helped the issue :)

**Closed** 2017-08-07 17:16 UTC

**Comment by PeterBowater** [comment] 2018-03-05 09:17
This seems to have resurfaced for me, behind a load balancer, and Varnish, and having to comment out these lines:

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/content/dataCollection/dataCollectionBean.cfc#L264-L268
