### ISSUE TITLE
Issue with using the same title for content and form

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#2911] opened 2018-07-27 14:29 UTC
Hi,

I've created a form called contact us without any issue, I then created a page called contact us and everything seems to work as expected. I then tried to update my form, i now get an error "The 'Title' that you entered is already in use.".

There seems to be a conflict with the titles and it doesn't allow me to update my form yet I'm able to update my page. I'm not sure if this is intended or if it's an bug.

I'm using Mura v7.1.238 

Thank you

**Comment by JonasEriksson** [comment] 2018-07-28 16:50
Hi, I am not certain, but it could be that forms and pages are treated in a similar way inside the Mura DB, so perhaps the easiest is to use slightly different names (perhaps contact_us_form for the form - that name does not need to show up anywhere usually and/or can be disabled from being displayed).

**Comment by mattlevine** [comment] 2018-08-01 17:44
https://github.com/blueriver/MuraCMS/commit/24b3d1c126dacc32f2b0256ebba207edf10f70ae

This issue should be resolved in the latest build 7.1.244

**Closed by mattlevine** 2018-08-01 17:44 UTC

**Comment by damien-git** [comment] 2018-08-27 13:02
Is this a duplicate of https://github.com/blueriver/MuraCMS/issues/2896 ? If so, maybe that bug can be closed too.
