### ISSUE TITLE
required true on extended attribute not working anymore?

### ISSUE THREAD

**Issue by Ronner** [blueriver/MuraCMS#1988] opened 2015-10-19 08:35 UTC
It seems that required=true on an extended attribute is not working anymore. I am using 6.2.6413 and a colleague has the same issue on 6.2.6403.

To reproduce, do the following:
- Create a class extension of type "page" subtype "whatever"
- Create an attribute set and give it a name
- Create an attribute, give it a name and set required to true and message to "Any message you want"

Now go to the site manager and create some content of that type. Leave the created attribute emtpy and click on publish. An error message is expected, but is not shown and the content is simply saved.

**Comment by Ronner** [comment] 2016-11-19 15:54
Opened this issue about a year ago. No comments or any feed back and then a year later it just get's closed without any information whether this was/is a bug. Strange way of communicating.

**Comment by mattlevine** [comment] 2016-11-19 17:27
Sorry about that, we're looking to improve our internal systems.  We we're not able to reproduce your issue.  If you are still experiencing it can you enable your Chrome debugger and and see if there's a JS error in the console or update to Mura 7 or manually update to the latest 6.2 by

1. Back everything up.
2. Download the latest in the 6.2 branch  https://github.com/blueriver/MuraCMS/tree/6.2
3. Copy your /config/settings.ini.cfm to a safe place
4. Copy everything except the "default" director from the downloaded zip into your Mura root.
5. Put you saved /config/settings.ini.cfm back.
5. Make a request to your Mura root in the browser with ?appreload&applydbupdates in the url.  If you have changed your appreload key replace "appreload" with your value.

Thanks,
-Matt

**Comment by shawna-mura** [comment] 2017-03-21 18:27
I'm closing this ticket and considering it resolved. If this issue persists, feel free to re-open with any new information that is relevant to the problem listed above. Thanks!

**Closed by shawna-mura** 2017-03-21 18:27 UTC
