### ISSUE TITLE
Clean install of master branch gives db errors

### ISSUE THREAD

**Issue by chexy** [blueriver/MuraCMS#1765] opened 2015-02-05 18:46 UTC
Hello All,
I recently deployed a copy of the Master branch to CF11 with a mysql db and received a number of errors related to missing Ad Manager tables.
The install went well with the setup screen creating the database and letting me into the admin afterwards.  I ran a core code update and this seems to be when the errors started.

This may be related to changes made back on Nov 14, 2014

This is not critical, I'm just testing on a new CF 11 deploy.

Thanks,

**Comment by mattlevine** [comment] 2015-02-05 19:40
Could you re-download and retest the installation?  I Think errors have
been fixed.

-matt

**Comment by chexy** [comment] 2015-02-06 17:42
Hey Matt,
No dice.  After the clean install my first error was this:
500 Error
The specified directory D:\home\cf11devsite\wwwroot\default\includes\themes\MuraBootstrap3/compiled could not be created.
The most likely cause of this error is that D:\home\cf11devsite\wwwroot\default\includes\themes\MuraBootstrap3/compiled already exists on your file system.

I can confirm that the folder does not exist in the zip file and now exists on the server.  So it created the folder during install but failed to put anything in it.

After a browser refresh with a different bug I logged into the admin and ran an appreload and the homepage of the site now loads.
Attempting a core code update shows the original problem.  After seeing the following message...

Your core files have been updated to version 6.2.6103.
Updated Files (2829) 

I clicked on the "view site list" button I get the original error
ErrorCode 	1146
Message 	Table 'db_cf11dev.tadcreatives' doesn't exist 

Here is a bit of the trace log
1 	
struct
COLUMN 	0
ID 	CFQUERY
LINE 	3
RAW_TRACE 	at cf52e02e7462ecfm538549798.runPage(D:\home\cf11devsite\wwwroot\requirements\mura\dbUpdates\5.0.746.cfm:3)
TEMPLATE 	D:\home\cf11devsite\wwwroot\requirements\mura\dbUpdates\5.0.746.cfm
TYPE 	CFML
2 	
struct
COLUMN 	0
ID 	CFINCLUDE
LINE 	821
RAW_TRACE 	at cfconfigBean2ecfc920188074$funcAPPLYDBUPDATES.runFunction(D:\home\cf11devsite\wwwroot\requirements\mura\configBean.cfc:821)
TEMPLATE 	D:\home\cf11devsite\wwwroot\requirements\mura\configBean.cfc
TYPE 	CFML
3 	
struct
COLUMN 	0
ID 	CF_TEMPLATEPROXY
LINE 	274
RAW_TRACE 	at cfonApplicationStart_include2ecfm1580756870._factor16(D:\home\cf11devsite\wwwroot\config\appcfc\onApplicationStart_include.cfm:274)
TEMPLATE 	D:\home\cf11devsite\wwwroot\config\appcfc\onApplicationStart_include.cfm
TYPE 	CFML
4 	
struct
COLUMN 	0
ID 	CF_ONAPPLICATIONSTART_INCLUDE
LINE 	102
RAW_TRACE 	at cfonApplicationStart_include2ecfm1580756870._factor24(D:\home\cf11devsite\wwwroot\config\appcfc\onApplicationStart_include.cfm:102)
TEMPLATE 	D:\home\cf11devsite\wwwroot\config\appcfc\onApplicationStart_include.cfm
TYPE 	CFML
5 	
struct
COLUMN 	0
ID 	CF_ONAPPLICATIONSTART_INCLUDE
LINE 	1
RAW_TRACE 	at cfonApplicationStart_include2ecfm1580756870.runPage(D:\home\cf11devsite\wwwroot\config\appcfc\onApplicationStart_include.cfm:1)
TEMPLATE 	D:\home\cf11devsite\wwwroot\config\appcfc\onApplicationStart_include.cfm
TYPE 	CFML
6 	
struct
COLUMN 	0
ID 	CFINCLUDE
LINE 	103
RAW_TRACE 	at cfonRequestStart_include2ecfm762722089._factor0(D:\home\cf11devsite\wwwroot\config\appcfc\onRequestStart_include.cfm:103)
TEMPLATE 	D:\home\cf11devsite\wwwroot\config\appcfc\onRequestStart_include.cfm
TYPE 	CFML
7 	
struct
COLUMN 	0
ID 	CF_ONREQUESTSTART_INCLUDE
LINE 	86
RAW_TRACE 	at cfonRequestStart_include2ecfm762722089._factor2(D:\home\cf11devsite\wwwroot\config\appcfc\onRequestStart_include.cfm:86)
TEMPLATE 	D:\home\cf11devsite\wwwroot\config\appcfc\onRequestStart_include.cfm
TYPE 	CFML
8 	
struct
COLUMN 	0
ID 	CF_ONREQUESTSTART_INCLUDE
LINE 	1
RAW_TRACE 	at cfonRequestStart_include2ecfm762722089.runPage(D:\home\cf11devsite\wwwroot\config\appcfc\onRequestStart_include.cfm:1)
TEMPLATE 	D:\home\cf11devsite\wwwroot\config\appcfc\onRequestStart_include.cfm
TYPE 	CFML
9 	
struct
COLUMN 	0
ID 	CFINCLUDE
LINE 	165
RAW_TRACE 	at cfApplication2ecfc459372825$funcONREQUESTSTART.runFunction(D:\home\cf11devsite\wwwroot\admin\Application.cfc:165)
TEMPLATE 	D:\home\cf11devsite\wwwroot\admin\Application.cfc
TYPE 	CFML

**Comment by mattlevine** [comment] 2015-02-07 08:26
This strange because the reference to the ad manager should be commented
out in the most recent codebase:

https://github.com/blueriver/MuraCMS/blob/master/requirements/mura/dbUpdates/5.0.746.cfm

Can you try setting your editing your /config/settings.ini.cfm and setting
autoupdatemode=preview and the click to update your core again?  Or
manually update and then make a root request with you appreload key and
applydbupdates

?appreload&applydupdates

**Comment by chexy** [comment] 2015-02-10 17:33
Hey Matt,
Using the preview release seemed to work so I guess you have fixed this and
just not merged it into the master yet.  Cool

The admin functions and the front end displays the default site with no
errors.

One step closer.  Now when I try to create a new site in the admin it seems
to create it in the database but not list it in the Global Settings page?

Version information

Core Version: 6.2.6142
Site Version: 6.2.6142
App Server: ColdFusion (11,0,03,292480)
DB Server: MySQL (5.6.22)
OS Version: Windows Server 2012 (6.2)

Thank you!

**Comment by chexy** [comment] 2015-02-10 23:40
Hey Matt,
Ok, I think I made some progress here on the site creation issue
I edited my settings.ini.cmf and added the dbusername and dppassword values for my database and saved the file, reloaded the application and poof...I see my created sites.

I have taken it as part of the default install, not to add my db username and password to the settings.ini.cfm file.  Has this changed?

Chexy

**Comment by mattlevine** [comment] 2015-02-10 23:41
I don't think it had to do with editing your settings.ini.cfm rather simply reloading Mura.

**Comment by chexy** [comment] 2015-02-10 23:46
Aw man, I have been reloading Mura all day, clearing the cache on the server, and querying the db directly.
I ended up going into the csettings/list.cfm file and dumping rs.rssites to see that the values were not updating in the object but they were in the database.
Editing the default site values and returning to the list still showed no changes.
Maybe a cache of the object finally expired? I don't know but after I updated the values in the settings.ini.cfm it kicked in immediately.
I will try removing the values in a little while to see if I can roll back the fix.

**Comment by chexy** [comment] 2015-02-11 04:48
Ok, I'm back in the saddle and rolled back my settings.ini.cfm change, reloaded the application and the newly created sites are gone again in the global settings listing.
I add the db username and password back into the settings.ini.cfm and reloaded the application again.  The sites returned in the global settings listing.

Very strange.

**Comment by chexy** [comment] 2015-02-11 20:48
While reviewing this with fresher eyes this morning the change does not fix the problem.
I tried adding a new site again to the same install this morning and it is not listed in the Global settings area.  My thoughts are going back to caching in cf 11.  I will continue reviewing this.

**Comment by mattlevine** [comment] 2015-02-11 20:52
I can't seem to reproduce the issue of the newly created site not showing up with either CF11 or Lucee?

**Comment by manking109** [comment] 2015-02-22 13:39
Chexy look in the data source advanced setting make sure all the check boxes for insert, select, ... are checked in cf11 they all check when creating database.

Manny

**Comment by chexy** [comment] 2015-03-07 05:09
Hello All,  
Sorry for the delay getting back to you all.
The recent updates in 6.2.6192 seem to have worked for the site listing issue.

@manking109 and @mattlevine, Thank you for looking into this!

Chexy

**Comment by stevewithington** [comment] 2015-03-07 05:11
Thanks for letting us know. Closing ticket.

**Closed by stevewithington** 2015-03-07 05:11 UTC
